//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalBandBakery.Infra.NameService.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameService.WCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductName", ReplyAction="http://tempuri.org/IService/GetProductNameResponse")]
        string GetProductName(char product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductName", ReplyAction="http://tempuri.org/IService/GetProductNameResponse")]
        System.Threading.Tasks.Task<string> GetProductNameAsync(char product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProducts", ReplyAction="http://tempuri.org/IService/GetAllProductsResponse")]
        string[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProducts", ReplyAction="http://tempuri.org/IService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<string[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductSort", ReplyAction="http://tempuri.org/IService/GetProductSortResponse")]
        char GetProductSort(string product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductSort", ReplyAction="http://tempuri.org/IService/GetProductSortResponse")]
        System.Threading.Tasks.Task<char> GetProductSortAsync(string product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProductSorts", ReplyAction="http://tempuri.org/IService/GetAllProductSortsResponse")]
        char[] GetAllProductSorts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProductSorts", ReplyAction="http://tempuri.org/IService/GetAllProductSortsResponse")]
        System.Threading.Tasks.Task<char[]> GetAllProductSortsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MetalBandBakery.Infra.NameService.WCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MetalBandBakery.Infra.NameService.WCF.IService>, MetalBandBakery.Infra.NameService.WCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetProductName(char product) {
            return base.Channel.GetProductName(product);
        }
        
        public System.Threading.Tasks.Task<string> GetProductNameAsync(char product) {
            return base.Channel.GetProductNameAsync(product);
        }
        
        public string[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public char GetProductSort(string product) {
            return base.Channel.GetProductSort(product);
        }
        
        public System.Threading.Tasks.Task<char> GetProductSortAsync(string product) {
            return base.Channel.GetProductSortAsync(product);
        }
        
        public char[] GetAllProductSorts() {
            return base.Channel.GetAllProductSorts();
        }
        
        public System.Threading.Tasks.Task<char[]> GetAllProductSortsAsync() {
            return base.Channel.GetAllProductSortsAsync();
        }
    }
}
